### PR TITLE
Added aditional functionality

### PR DESCRIPTION
**Pull request by sperlchris**
Redesign of API, implemented most functionality of leaflet JavaScript library.

### CODE REVIEW

**Comment by jtulach** [comment]
Thanks for your request, I am (finally) looking at it. First of all I tried:
```
$ git clone https://github.com/sperlchris/leaflet4j.git
$ cd leaflet4j
$ mvn clean install
```
and the build fails. I would expect something as basic to work before requesting an integration.

**Comment by jtulach** [comment]
I can skip the overall build and go directly to the api project, but tell me, how one generates a Javadoc? I tried:

$ cd api
$ mvn clean package javadoc:javadoc

the Javadoc step fails on JDK 1.8.0_40. I tried to generate the Javadoc with JDK7, but it fails too, as you are using lambdas.

I am currious to know how have you verified your documentation is sufficient? Are you able to generate Javadoc somehow?

**Comment by sperlchris** [comment]
Sorry for the problems. We are new to maven and had some starting problems.
You have been right, there was some bug with the licence headers and the javadoc. Therefore your compilation and javadoc generation failed.
We have fixed these issues. Please look at our repository and give us some feedback.
Thank you!

**Comment by jtulach** [comment]
I can build the code and the javadoc with JDK8. Thanks.

1. - I can see there is whole a lot of classes (more than 70) in the API. That is quite a lot. It makes it really hard to find the entry point to the API. Having the README.md exemple in Javadoc would be beneficial.

2. I still see some implementation details exposed. The ILayer (btw. why "I"?) still exposes jsObj field. Also the class has tons of protected static methods. Imho unnecessary.

3. Some classes are subclassable and I am not sure why they should be. For example Rectangle.

Otherwise I think you did good job in covering various aspects of the leaflet4j library. I like capabilities of your API. I will pick what you have up, fix mistakes (like 2, 3) and polish it to better suite my (subjective) taste.

Thanks for your contribution!

**Comment by sperlchris** [comment]
Thanks again for your feedback.
Ad 2.: ILayer does not completely expose jsObj, only if you inherit from ILayer. This thing and also the bunch of protected static methods are needed for custom layers. We added a sample custom layer in the demo. If you want to implement your own layer you have to deal with java script objects - there is no other way. If you don't need your own layer and therefore don't inherit from ILayer, you will never have access to any java script object.
We hope our approach makes sense for you.
The name ILayer comes from the java script equivalent - we can rename it to Layer, we don't really mind.

**Comment by jtulach** [comment]
I have to admit I don't understand the custom layers much. The duck example is trivial and I could certainly think about coding it without JavaScript. I took a look at http://leafletjs.com/reference.html#ilayer and yes, such example would certainly require usage of JavaScript.  On the other hand I believe API/SPI should be separated. There should be different API (e.g. SPI) for those who want to write custom layers. 

If we change all objects in the org.apidesign.html.leaflet.api package to non-subclassable will it hurt one of your use-cases (except the custom layer)?

**Comment by agrimmer** [comment]
Our last commit makes all classes which are not used as base class final.
We use in certain cases inheritance to get a small API, e.g., methods take a general type and it is not necessary to override the method for all sub-types.

**Comment by jtulach** [comment]
Yeah, I have seen many classes being final. But the "base classes" are
still subclassable by the end user. If that is not the intended use (and I
hope it is not), I'd advocate to prevent that. The cheap trick to prevent
subclassing of non-final classes is to provide only package private
constructor. That prevents API users from subclassing, but also removes the
ability to construct the class from the API - in case API users are
supposed to create such instances, I would provide static factory method to
create the class.

-jt


2015-04-01 14:35 GMT+02:00 agrimmer <notifications@github.com>:

**Comment by jtulach** [comment]
I am ready to accept the request after few tweaks. The javadoc is available at http://hudson.apidesign.org/hudson/job/leaflet4j/javadoc/

One additional question is EPSG3395 & etc. imho the API is unusable in current state. Or can somebody tell me how it should be used? Thanks.

**Comment by swurzinger** [comment]
When creating a map it is configured using MapOptions. A CRS can be set in this configuration object:
```java
    MapOptions mapOptions = new MapOptions() 
        .setCenter(new LatLng(48.336614, 14.319305)) 
        .setZoom(15) 
        .setCRS(EPSG3395.get());
    final Map map = new Map("map", mapOptions); 
```
Additionally all methods of the base class (ICRS) are supported, which allow (manual) coordinate/point conversions according to the rules of the specific coordinate reference system.

**Comment by jtulach** [comment]
The problem is that EPSG3395.get is not static method. Probably nobody tried the described usecase for real. I can make the method static, but does it make sense? Isn't it better to all these CRS implementations package private and put various

public static ICRS getEPSG3395()

methods into ICRS class itself? It would lower the number of visible classes in API which is usually a good thing. Moreover the method would only be visible to those who take a look at the ICRS class (e.g. have an interest in it), while currently the classes are visible for everyone, even those who don't care about ICRS at all.

**Comment by jtulach** [comment]
Here is my proposed change: ea90d3fe2e3aadc14a5c10dad692e1781816e31f

**Comment by swurzinger** [comment]
The getters were intended to be static indeed, but that functionality wasn't tested.
I agree that "hiding" the CRS classes is a good thing as they probably won't be used by the majority of the users of the API.
One thing you may keep in mind is that a future version of the API might allow the user to implement custom CRSs, which are not possible with the current API.

**Comment by jtulach** [comment]
Merged with few tweaks as d850a5aa68fda47294683a17d26d7d531632405f - thanks for your contribution. Now it is time to work on a release.

**Pull request closed without merging**
